// Package tools provides a plugin-based tool system for the Claude CLI.
// It defines the Tool interface that all tools must implement, along with
// common types and utilities for tool execution.
package tools

import (
	"context"

	"github.com/user-name/cc-cli-go/internal/types"
)

// ToolResult represents the result of a tool execution.
// It can contain either a successful result or an error message.
type ToolResult struct {
	// Content holds the result value (string or structured data)
	Content interface{}
	// IsError indicates whether the execution failed
	IsError bool
	// NewMessages contains any additional messages generated by the tool
	NewMessages []*types.Message
}

// PermissionResult represents the result of a permission check.
type PermissionResult struct {
	// Behavior indicates the permission decision (allow/deny/ask)
	Behavior string
	// Reason provides context for the decision
	Reason string
}

// ToolContext provides context information for tool execution.
type ToolContext struct {
	// WorkingDir is the current working directory
	WorkingDir string
	// AbortSignal allows cancellation of long-running operations
	AbortSignal context.Context
}

// Tool defines the interface that all tools must implement.
// Tools are plugins that extend Claude's capabilities (e.g., file operations,
// shell commands, etc.).
type Tool interface {
	// Name returns the tool's identifier (e.g., "Read", "Write")
	Name() string
	// Description returns a human-readable description of the tool's purpose
	Description() string
	// InputSchema returns the JSON schema for the tool's input parameters
	InputSchema() map[string]interface{}

	// Execute runs the tool with the given input and context
	Execute(ctx context.Context, input map[string]interface{}, tc *ToolContext) (*ToolResult, error)

	// IsEnabled returns whether the tool is currently available
	IsEnabled() bool
	// IsReadOnly returns whether the tool only reads data (no side effects)
	IsReadOnly(input map[string]interface{}) bool
	// IsConcurrencySafe returns whether the tool can be run in parallel with other instances
	IsConcurrencySafe(input map[string]interface{}) bool

	// UserFacingName returns a user-friendly name for display purposes
	UserFacingName(input map[string]interface{}) string
}

// ToToolParam converts a Tool to the API's tool parameter format.
// This is used when sending tool definitions to the Claude API.
func ToToolParam(t Tool) map[string]interface{} {
	return map[string]interface{}{
		"name":         t.Name(),
		"description":  t.Description(),
		"input_schema": t.InputSchema(),
	}
}
